# Generated by Django 5.0 on 2025-08-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('is_published', models.BooleanField(default=False, verbose_name='게시 여부')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='메타 제목')),
                ('meta_description', models.TextField(blank=True, verbose_name='메타 설명')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='메타 키워드')),
                ('enable_comments', models.BooleanField(default=True, verbose_name='댓글 허용')),
                ('enable_likes', models.BooleanField(default=True, verbose_name='좋아요 허용')),
            ],
            options={
                'verbose_name': '페이지',
                'verbose_name_plural': '페이지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿 이름')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('template_type', models.CharField(choices=[('single', '단일 컬럼'), ('two-column', '2컬럼'), ('three-column', '3컬럼'), ('hero', '히어로 페이지'), ('gallery', '갤러리'), ('custom', '커스텀')], default='single', max_length=20, verbose_name='템플릿 타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('html_template', models.TextField(blank=True, verbose_name='HTML 템플릿')),
                ('css_styles', models.TextField(blank=True, verbose_name='CSS 스타일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '템플릿',
                'verbose_name_plural': '템플릿 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='파일')),
                ('media_type', models.CharField(choices=[('image', '이미지'), ('video', '비디오'), ('document', '문서'), ('other', '기타')], default='image', max_length=20, verbose_name='미디어 타입')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='대체 텍스트')),
                ('caption', models.TextField(blank=True, verbose_name='캡션')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='너비')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='높이')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '미디어',
                'verbose_name_plural': '미디어 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('block_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('gallery', '갤러리'), ('video', '비디오'), ('html', 'HTML'), ('map', '지도'), ('contact', '연락처'), ('spacer', '여백')], max_length=20, verbose_name='블록 타입')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('settings_json', models.TextField(default='{}', verbose_name='설정')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='CSS 클래스')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시 여부')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pagebuilder.page', verbose_name='페이지')),
            ],
            options={
                'verbose_name': '블록',
                'verbose_name_plural': '블록 목록',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagebuilder.template', verbose_name='템플릿'),
        ),
    ]
