# Generated by Django 5.0 on 2025-08-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='금지어')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='카테고리')),
                ('severity', models.IntegerField(default=5, verbose_name='심각도 (1-10)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '금지어',
                'verbose_name_plural': '금지어 목록',
                'ordering': ['category', 'word'],
            },
        ),
        migrations.CreateModel(
            name='FilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='규칙 이름')),
                ('rule_type', models.CharField(choices=[('word', '단어'), ('pattern', '패턴'), ('regex', '정규식'), ('url', 'URL')], default='word', max_length=20, verbose_name='규칙 타입')),
                ('pattern', models.CharField(max_length=500, verbose_name='패턴')),
                ('replacement', models.CharField(blank=True, default='***', max_length=100, verbose_name='대체 텍스트')),
                ('action', models.CharField(choices=[('block', '차단'), ('replace', '대체'), ('review', '검토'), ('warning', '경고')], default='replace', max_length=20, verbose_name='액션')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('severity', models.IntegerField(default=1, verbose_name='심각도 (1-10)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_case_sensitive', models.BooleanField(default=False, verbose_name='대소문자 구분')),
                ('match_count', models.IntegerField(default=0, verbose_name='매칭 횟수')),
            ],
            options={
                'verbose_name': '필터 규칙',
                'verbose_name_plural': '필터 규칙 목록',
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='패턴 이름')),
                ('pattern', models.TextField(verbose_name='패턴')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_regex', models.BooleanField(default=False, verbose_name='정규식 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('detection_count', models.IntegerField(default=0, verbose_name='감지 횟수')),
            ],
            options={
                'verbose_name': '스팸 패턴',
                'verbose_name_plural': '스팸 패턴 목록',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('content_type', models.CharField(choices=[('comment', '댓글'), ('post', '게시물'), ('message', '메시지'), ('other', '기타')], max_length=20, verbose_name='콘텐츠 타입')),
                ('original_content', models.TextField(verbose_name='원본 내용')),
                ('filtered_content', models.TextField(blank=True, verbose_name='필터링된 내용')),
                ('result', models.CharField(choices=[('passed', '통과'), ('blocked', '차단'), ('replaced', '대체'), ('review', '검토 대기'), ('warning', '경고')], max_length=20, verbose_name='결과')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검토 완료')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('review_notes', models.TextField(blank=True, verbose_name='검토 노트')),
                ('matched_rules', models.ManyToManyField(blank=True, to='moderation.filterrule', verbose_name='매칭된 규칙')),
                ('matched_words', models.ManyToManyField(blank=True, to='moderation.blockedword', verbose_name='매칭된 금지어')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '검열 로그',
                'verbose_name_plural': '검열 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
