# Generated by Django 5.0 on 2025-08-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=100, verbose_name='메뉴 제목')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('menu_type', models.CharField(choices=[('page', '페이지 링크'), ('external', '외부 링크'), ('section', '섹션 앵커')], default='page', max_length=20, verbose_name='메뉴 타입')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘 클래스')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시 여부')),
                ('target_blank', models.BooleanField(default=False, verbose_name='새창 열기')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='메타 제목')),
                ('meta_description', models.TextField(blank=True, verbose_name='메타 설명')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigator.menuitem', verbose_name='상위 메뉴')),
            ],
            options={
                'verbose_name': '메뉴 아이템',
                'verbose_name_plural': '메뉴 아이템 목록',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
