# Generated by Django 5.0 on 2025-08-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('object_id', models.PositiveIntegerField()),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='작성자명(비회원)')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='이메일(비회원)')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_approved', models.BooleanField(default=True, verbose_name='승인 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='필터링됨')),
                ('filtered_reason', models.CharField(blank=True, max_length=200, verbose_name='필터링 사유')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interaction.comment')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='interaction_content_d01ec1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteractionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('scope', models.CharField(choices=[('global', '전체 시스템'), ('menu', '메뉴 단위'), ('page', '페이지 단위')], default='global', max_length=20, verbose_name='적용 범위')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enable_comments', models.BooleanField(default=True, verbose_name='댓글 허용')),
                ('enable_likes', models.BooleanField(default=True, verbose_name='좋아요 허용')),
                ('enable_views', models.BooleanField(default=True, verbose_name='조회수 표시')),
                ('require_login_for_comment', models.BooleanField(default=False, verbose_name='댓글 로그인 필수')),
                ('auto_approve_comments', models.BooleanField(default=True, verbose_name='댓글 자동 승인')),
                ('enable_nested_comments', models.BooleanField(default=True, verbose_name='대댓글 허용')),
                ('max_comment_depth', models.IntegerField(default=2, verbose_name='대댓글 최대 깊이')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '상호작용 설정',
                'verbose_name_plural': '상호작용 설정 목록',
                'unique_together': {('scope', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요 목록',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='interaction_content_a5ee60_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '조회',
                'verbose_name_plural': '조회 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='interaction_content_3f61e8_idx'), models.Index(fields=['ip_address'], name='interaction_ip_addr_7db9d4_idx')],
            },
        ),
    ]
