# Generated by Django 5.0 on 2025-10-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='인사말', max_length=200, verbose_name='제목')),
                ('content_1', models.TextField(verbose_name='첫 번째 문단')),
                ('content_2', models.TextField(verbose_name='두 번째 문단')),
                ('content_3', models.TextField(verbose_name='세 번째 문단')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='전시장 내부 이미지')),
                ('image_1_title', models.CharField(default='전시장 내부', max_length=100, verbose_name='이미지1 제목')),
                ('image_1_desc', models.CharField(default='하나아트갤러리 전시 공간', max_length=200, verbose_name='이미지1 설명')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='전시장 도면 이미지')),
                ('image_2_title', models.CharField(default='전시장 도면', max_length=100, verbose_name='이미지2 제목')),
                ('image_2_desc', models.CharField(default='갤러리 평면도', max_length=200, verbose_name='이미지2 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '인사말',
                'verbose_name_plural': '인사말 목록',
            },
        ),
        migrations.CreateModel(
            name='ArtFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='아트페어명')),
                ('description', models.TextField(verbose_name='설명')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('image', models.ImageField(upload_to='artfairs/', verbose_name='이미지')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '아트페어',
                'verbose_name_plural': '아트페어 목록',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='작가명')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='영문명')),
                ('description', models.TextField(verbose_name='작가 설명')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='프로필 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='하나아트갤러리 본점(인사동)', max_length=200, verbose_name='제목')),
                ('ceo_name', models.CharField(max_length=100, verbose_name='대표자명')),
                ('ceo_name_en', models.CharField(blank=True, max_length=100, verbose_name='대표자 영문명')),
                ('phone', models.CharField(max_length=50, verbose_name='전화번호')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='팩스번호')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='휴대전화')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('address', models.TextField(verbose_name='주소')),
                ('address_en', models.TextField(blank=True, verbose_name='영문 주소')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '연락처',
                'verbose_name_plural': '연락처 목록',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='액자 제작', max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('image_1', models.ImageField(upload_to='frames/', verbose_name='액자 이미지 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='frames/', verbose_name='액자 이미지 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='frames/', verbose_name='액자 이미지 3')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '액자',
                'verbose_name_plural': '액자 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '연혁',
                'verbose_name_plural': '연혁 목록',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HomeDesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(choices=[('premium_grid', '프리미엄 그리드 모자이크 (GSAP + Lenis + GLSL Shaders)'), ('cube_3d', '3D 큐브 갤러리 (Three.js + WebGL)'), ('cinematic', '시네마틱 풀스크린 슬라이더 (영화급 트랜지션)')], default='premium_grid', help_text='수억원급 프리미엄 홈 디자인 선택', max_length=20, verbose_name='디자인 타입')),
                ('is_active', models.BooleanField(default=True, verbose_name='현재 활성화')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 변경')),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='변경자')),
            ],
            options={
                'verbose_name': '홈 디자인 설정',
                'verbose_name_plural': '홈 디자인 설정',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('home', '홈'), ('about', '인사말'), ('history', '연혁'), ('exhibition', '전시'), ('artfair', '아트페어'), ('artist', '작가'), ('frame', '액자제작'), ('contact', '연락처')], max_length=50, unique=True, verbose_name='템플릿명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '템플릿',
                'verbose_name_plural': '템플릿 목록',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='작품명')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='영문 작품명')),
                ('description', models.TextField(blank=True, verbose_name='작품 설명')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='작품 이미지')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='제작년도')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='크기')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='재료')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_featured', models.BooleanField(default=False, help_text='홈 페이지 히어로 섹션에 노출됩니다', verbose_name='메인 히어로 노출')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artist', verbose_name='작가')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품 목록',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='전시명')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='영문 전시명')),
                ('description', models.TextField(verbose_name='전시 설명')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='전시 장소')),
                ('start_date', models.DateField(verbose_name='전시 시작일')),
                ('end_date', models.DateField(verbose_name='전시 종료일')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/', verbose_name='포스터 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to='gallery.artist', verbose_name='작가')),
            ],
            options={
                'verbose_name': '전시',
                'verbose_name_plural': '전시 목록',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='섹션명')),
                ('section_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('gallery', '갤러리'), ('list', '리스트')], max_length=20, verbose_name='섹션 타입')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='gallery.template', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '템플릿 섹션',
                'verbose_name_plural': '템플릿 섹션 목록',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='gallery.artwork', verbose_name='작품')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_artworks', to='gallery.exhibition', verbose_name='전시')),
            ],
            options={
                'verbose_name': '전시 작품',
                'verbose_name_plural': '전시 작품 목록',
                'ordering': ['exhibition', 'order'],
                'unique_together': {('exhibition', 'artwork')},
            },
        ),
    ]
