# Generated by Django 5.0 on 2025-08-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='작가명')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='영문명')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='출생년도')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artists/profiles/', verbose_name='프로필 이미지')),
                ('bio', models.TextField(blank=True, verbose_name='약력')),
                ('education', models.TextField(blank=True, verbose_name='학력')),
                ('awards', models.TextField(blank=True, verbose_name='수상경력')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='인스타그램')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='전속작가')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가 목록',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='작품명')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='영문 작품명')),
                ('artwork_type', models.CharField(choices=[('painting', '회화'), ('sculpture', '조각'), ('photography', '사진'), ('installation', '설치'), ('media', '미디어'), ('craft', '공예'), ('other', '기타')], default='painting', max_length=20, verbose_name='작품 유형')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='제작년도')),
                ('medium', models.CharField(blank=True, max_length=200, verbose_name='재료/기법')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='크기')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='에디션')),
                ('description', models.TextField(blank=True, verbose_name='작품 설명')),
                ('main_image', models.ImageField(upload_to='artworks/', verbose_name='메인 이미지')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artworks/thumbs/', verbose_name='썸네일')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='가격')),
                ('is_sold', models.BooleanField(default=False, verbose_name='판매 완료')),
                ('is_for_sale', models.BooleanField(default=True, verbose_name='판매 가능')),
                ('is_featured', models.BooleanField(default=False, verbose_name='대표작품')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artist', verbose_name='작가')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품 목록',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('image', models.ImageField(upload_to='artworks/additional/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='캡션')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='gallery.artwork', verbose_name='작품')),
            ],
            options={
                'verbose_name': '작품 이미지',
                'verbose_name_plural': '작품 이미지 목록',
                'ordering': ['artwork', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='전시명')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='영문 전시명')),
                ('exhibition_type', models.CharField(choices=[('solo', '개인전'), ('group', '단체전'), ('special', '특별전'), ('fair', '아트페어')], default='solo', max_length=20, verbose_name='전시 유형')),
                ('description', models.TextField(blank=True, verbose_name='전시 설명')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/posters/', verbose_name='포스터 이미지')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('opening_date', models.DateTimeField(blank=True, null=True, verbose_name='오프닝 일시')),
                ('venue', models.CharField(default='하나아트갤러리', max_length=200, verbose_name='장소')),
                ('venue_address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 전시')),
                ('is_featured', models.BooleanField(default=False, verbose_name='대표 전시')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('meta_description', models.TextField(blank=True, verbose_name='메타 설명')),
                ('artists', models.ManyToManyField(related_name='exhibitions', to='gallery.artist', verbose_name='참여 작가')),
            ],
            options={
                'verbose_name': '전시',
                'verbose_name_plural': '전시 목록',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='exhibitions',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='gallery.exhibition', verbose_name='전시'),
        ),
    ]
