# Generated by Django 5.0 on 2025-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=200, verbose_name='전시명')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='부제')),
                ('artist_name', models.CharField(max_length=100, verbose_name='작가명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('venue', models.CharField(default='하나아트갤러리', max_length=200, verbose_name='장소')),
                ('description', models.TextField(verbose_name='전시 설명')),
                ('image1', models.ImageField(upload_to='exhibitions/current/', verbose_name='메인 이미지')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='exhibitions/current/', verbose_name='이미지 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='exhibitions/current/', verbose_name='이미지 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '현재 전시',
                'verbose_name_plural': '현재 전시',
                'ordering': ['-created_at'],
            },
        ),
    ]
