# Generated by Django 5.0 on 2025-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_currentexhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=100, verbose_name='작가명')),
                ('bio', models.TextField(help_text='작가에 대한 간단한 소개', verbose_name='작가 소개')),
                ('artwork1', models.ImageField(upload_to='artists/simple/', verbose_name='작품 이미지 1')),
                ('artwork2', models.ImageField(blank=True, null=True, upload_to='artists/simple/', verbose_name='작품 이미지 2')),
                ('artwork3', models.ImageField(blank=True, null=True, upload_to='artists/simple/', verbose_name='작품 이미지 3')),
                ('display_order', models.IntegerField(default=0, help_text='낮은 숫자가 먼저 표시됩니다', verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '전속작가 (간단)',
                'verbose_name_plural': '전속작가 목록 (간단)',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
